
apiVersion: v1
kind: Service
metadata:
  name: helloservice
spec:
  selector:
    app: helloworld
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000


---

apiVersion: v1
kind: Service
metadata:
  name: redisservice
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379